//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.27 at 10:49:34 AM PDT 
//


package com.appdynamics.demo.metricservice.integration.ucs.in;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for apeMenloVnic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="apeMenloVnic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}apeMenloVnicStats"/>
 *       &lt;/choice>
 *       &lt;attribute name="cos" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="mac" type="{}addressMAC" />
 *       &lt;attribute name="pifId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="state">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Unknown"/>
 *             &lt;enumeration value="Present"/>
 *             &lt;enumeration value="Creating"/>
 *             &lt;enumeration value="Modifying"/>
 *             &lt;enumeration value="Destroying"/>
 *             &lt;enumeration value="CreatePend"/>
 *             &lt;enumeration value="ModifyPend"/>
 *             &lt;enumeration value="DestroyPend"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="uplinkPortId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="vifId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="vifType" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="vlanId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="vntag" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="wwnn" type="{}addressWWN" />
 *       &lt;attribute name="wwpn" type="{}addressWWN" />
 *       &lt;attribute name="cookie" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="510"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dn" type="{}referenceObject" />
 *       &lt;attribute name="rn" type="{}referenceRn" />
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="((removed|created|modified|deleted),){0,3}(removed|created|modified|deleted){0,1}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "apeMenloVnic", propOrder = {
    "content"
})
public class ApeMenloVnic {

    @XmlElementRef(name = "apeMenloVnicStats", type = JAXBElement.class, required = false)
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "cos")
    @XmlSchemaType(name = "unsignedByte")
    protected Short cos;
    @XmlAttribute(name = "mac")
    protected String mac;
    @XmlAttribute(name = "pifId")
    @XmlSchemaType(name = "unsignedByte")
    protected Short pifId;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "uplinkPortId")
    @XmlSchemaType(name = "unsignedByte")
    protected Short uplinkPortId;
    @XmlAttribute(name = "vifId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long vifId;
    @XmlAttribute(name = "vifType")
    @XmlSchemaType(name = "unsignedByte")
    protected Short vifType;
    @XmlAttribute(name = "vlanId")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer vlanId;
    @XmlAttribute(name = "vntag")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer vntag;
    @XmlAttribute(name = "wwnn")
    protected String wwnn;
    @XmlAttribute(name = "wwpn")
    protected String wwpn;
    @XmlAttribute(name = "cookie")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger cookie;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "dn")
    protected String dn;
    @XmlAttribute(name = "rn")
    protected String rn;
    @XmlAttribute(name = "status")
    protected String status;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ApeMenloVnicStats }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the cos property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCos() {
        return cos;
    }

    /**
     * Sets the value of the cos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCos(Short value) {
        this.cos = value;
    }

    /**
     * Gets the value of the mac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMac() {
        return mac;
    }

    /**
     * Sets the value of the mac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMac(String value) {
        this.mac = value;
    }

    /**
     * Gets the value of the pifId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPifId() {
        return pifId;
    }

    /**
     * Sets the value of the pifId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPifId(Short value) {
        this.pifId = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the uplinkPortId property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getUplinkPortId() {
        return uplinkPortId;
    }

    /**
     * Sets the value of the uplinkPortId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setUplinkPortId(Short value) {
        this.uplinkPortId = value;
    }

    /**
     * Gets the value of the vifId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVifId() {
        return vifId;
    }

    /**
     * Sets the value of the vifId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVifId(Long value) {
        this.vifId = value;
    }

    /**
     * Gets the value of the vifType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getVifType() {
        return vifType;
    }

    /**
     * Sets the value of the vifType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setVifType(Short value) {
        this.vifType = value;
    }

    /**
     * Gets the value of the vlanId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVlanId() {
        return vlanId;
    }

    /**
     * Sets the value of the vlanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVlanId(Integer value) {
        this.vlanId = value;
    }

    /**
     * Gets the value of the vntag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVntag() {
        return vntag;
    }

    /**
     * Sets the value of the vntag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVntag(Integer value) {
        this.vntag = value;
    }

    /**
     * Gets the value of the wwnn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWwnn() {
        return wwnn;
    }

    /**
     * Sets the value of the wwnn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWwnn(String value) {
        this.wwnn = value;
    }

    /**
     * Gets the value of the wwpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWwpn() {
        return wwpn;
    }

    /**
     * Sets the value of the wwpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWwpn(String value) {
        this.wwpn = value;
    }

    /**
     * Gets the value of the cookie property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCookie() {
        return cookie;
    }

    /**
     * Sets the value of the cookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCookie(BigInteger value) {
        this.cookie = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDn() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDn(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the rn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRn() {
        return rn;
    }

    /**
     * Sets the value of the rn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRn(String value) {
        this.rn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
