//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.27 at 10:49:34 AM PDT 
//


package com.appdynamics.demo.metricservice.integration.ucs.in;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for computeRackUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="computeRackUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}aaaEpUser"/>
 *         &lt;element ref="{}adaptorUnit"/>
 *         &lt;element ref="{}biosUnit"/>
 *         &lt;element ref="{}computeBoard"/>
 *         &lt;element ref="{}computeBoardController"/>
 *         &lt;element ref="{}computePoolable"/>
 *         &lt;element ref="{}computeScrubPolicy"/>
 *         &lt;element ref="{}diagSrvCtrl"/>
 *         &lt;element ref="{}equipmentFanModule"/>
 *         &lt;element ref="{}equipmentIndicatorLed"/>
 *         &lt;element ref="{}equipmentLocatorLed"/>
 *         &lt;element ref="{}equipmentPsu"/>
 *         &lt;element ref="{}fabricLocale"/>
 *         &lt;element ref="{}lsbootDef"/>
 *         &lt;element ref="{}mgmtController"/>
 *         &lt;element ref="{}pciUnit"/>
 *         &lt;element ref="{}powerBudget"/>
 *         &lt;element ref="{}solIf"/>
 *       &lt;/choice>
 *       &lt;attribute name="id">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="255"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="adminPower">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="cycle-immediate"/>
 *             &lt;enumeration value="cycle-wait"/>
 *             &lt;enumeration value="hard-reset-immediate"/>
 *             &lt;enumeration value="hard-reset-wait"/>
 *             &lt;enumeration value="diagnostic-interrupt"/>
 *             &lt;enumeration value="kvm-reset"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lc">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="undiscovered"/>
 *             &lt;enumeration value="rediscover"/>
 *             &lt;enumeration value="resetToFactory"/>
 *             &lt;enumeration value="discovered"/>
 *             &lt;enumeration value="remove"/>
 *             &lt;enumeration value="migrate"/>
 *             &lt;enumeration value="decommission"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="usrLbl">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[ !#$%&amp;\(\)\*\+,\-\./:;\?@\[\]_\{\|\}~a-zA-Z0-9]{0,32}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="descr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[ !#$%&amp;\(\)\*\+,\-\./:;\?@\[\]_\{\|\}~a-zA-Z0-9]{0,256}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[\-\.:_a-zA-Z0-9]{0,16}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dn" type="{}referenceObject" />
 *       &lt;attribute name="rn" type="{}referenceRn" />
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="((removed|created|modified|deleted),){0,3}(removed|created|modified|deleted){0,1}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "computeRackUnit", propOrder = {
    "content"
})
public class ComputeRackUnit {

    @XmlElementRefs({
        @XmlElementRef(name = "diagSrvCtrl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "equipmentFanModule", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "equipmentLocatorLed", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "solIf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "computeBoard", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lsbootDef", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "computeScrubPolicy", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "aaaEpUser", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "biosUnit", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "computePoolable", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pciUnit", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fabricLocale", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "computeBoardController", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "equipmentPsu", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "adaptorUnit", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mgmtController", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "powerBudget", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "equipmentIndicatorLed", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "adminPower")
    protected String adminPower;
    @XmlAttribute(name = "lc")
    protected String lc;
    @XmlAttribute(name = "usrLbl")
    protected String usrLbl;
    @XmlAttribute(name = "descr")
    protected String descr;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "dn")
    protected String dn;
    @XmlAttribute(name = "rn")
    protected String rn;
    @XmlAttribute(name = "status")
    protected String status;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DiagSrvCtrl }{@code >}
     * {@link JAXBElement }{@code <}{@link EquipmentFanModule }{@code >}
     * {@link JAXBElement }{@code <}{@link EquipmentLocatorLed }{@code >}
     * {@link JAXBElement }{@code <}{@link SolIf }{@code >}
     * {@link JAXBElement }{@code <}{@link ComputeBoard }{@code >}
     * {@link JAXBElement }{@code <}{@link LsbootDef }{@code >}
     * {@link JAXBElement }{@code <}{@link ComputeScrubPolicy }{@code >}
     * {@link JAXBElement }{@code <}{@link AaaEpUser }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link BiosUnit }{@code >}
     * {@link JAXBElement }{@code <}{@link ComputePoolable }{@code >}
     * {@link JAXBElement }{@code <}{@link PciUnit }{@code >}
     * {@link JAXBElement }{@code <}{@link FabricLocale }{@code >}
     * {@link JAXBElement }{@code <}{@link ComputeBoardController }{@code >}
     * {@link JAXBElement }{@code <}{@link EquipmentPsu }{@code >}
     * {@link JAXBElement }{@code <}{@link AdaptorUnit }{@code >}
     * {@link JAXBElement }{@code <}{@link MgmtController }{@code >}
     * {@link JAXBElement }{@code <}{@link PowerBudget }{@code >}
     * {@link JAXBElement }{@code <}{@link EquipmentIndicatorLed }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the adminPower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminPower() {
        return adminPower;
    }

    /**
     * Sets the value of the adminPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminPower(String value) {
        this.adminPower = value;
    }

    /**
     * Gets the value of the lc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLc() {
        return lc;
    }

    /**
     * Sets the value of the lc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLc(String value) {
        this.lc = value;
    }

    /**
     * Gets the value of the usrLbl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrLbl() {
        return usrLbl;
    }

    /**
     * Sets the value of the usrLbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrLbl(String value) {
        this.usrLbl = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescr() {
        return descr;
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescr(String value) {
        this.descr = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDn() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDn(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the rn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRn() {
        return rn;
    }

    /**
     * Sets the value of the rn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRn(String value) {
        this.rn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
