//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.27 at 10:49:34 AM PDT 
//


package com.appdynamics.demo.metricservice.integration.ucs.in;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statsThr64Definition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statsThr64Definition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}statsThr32Value"/>
 *         &lt;element ref="{}statsThr64Value"/>
 *         &lt;element ref="{}statsThrFloatValue"/>
 *       &lt;/choice>
 *       &lt;attribute name="normalValue" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="propId">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="adaptorEthPortStatspppPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortStatspppPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortStatspppPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortStatspppPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan64Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan64DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan64DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan64DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatsequals64Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatsequals64DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatsequals64DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatsequals64DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan128Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan128DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan128DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan128DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan256Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan256DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan256DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan256DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan512Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan512DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan512DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan512DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan1024Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan1024DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan1024DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeSmallStatslessThan1024DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThanOrEqualTo1518Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThanOrEqualTo1518DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThanOrEqualTo1518DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThanOrEqualTo1518DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan2048Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan2048DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan2048DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan2048DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan4096Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan4096DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan4096DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan4096DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan8192Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan8192DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan8192DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan8192DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan9216Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan9216DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan9216DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatslessThan9216DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsgreaterThanOrEqualTo9216Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsgreaterThanOrEqualTo9216DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsgreaterThanOrEqualTo9216DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsgreaterThanOrEqualTo9216DeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedGoodCrcPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedGoodCrcPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedGoodCrcPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedGoodCrcPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedBadCrcPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedBadCrcPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedBadCrcPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsoversizedBadCrcPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedGoodCrcPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedGoodCrcPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedGoodCrcPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedGoodCrcPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedBadCrcPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedBadCrcPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedBadCrcPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortOutsizedStatsundersizedBadCrcPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsunicastPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsunicastPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsunicastPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsunicastPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsmulticastPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsmulticastPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsmulticastPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsmulticastPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsbroadcastPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsbroadcastPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsbroadcastPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortMcastStatsbroadcastPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsmacDiscardedPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsmacDiscardedPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsmacDiscardedPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsmacDiscardedPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadCrcPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadCrcPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadCrcPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadCrcPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadLengthPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadLengthPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadLengthPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortErrStatsbadLengthPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxFramesDelta"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcPortStatstxFramesDelta"/>
 *             &lt;enumeration value="adaptorFcPortStatstxFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcPortStatstxFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcPortStatstxFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxBadFramesDelta"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxBadFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxBadFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcPortStatsrxBadFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcPortStatstxBadFramesDelta"/>
 *             &lt;enumeration value="adaptorFcPortStatstxBadFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcPortStatstxBadFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcPortStatstxBadFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsTxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsTxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsTxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsTxDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsRxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsRxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsRxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatspacketsRxDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesTxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesTxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesTxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesTxDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesRxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesRxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesRxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatsbytesRxDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsTxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsTxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsTxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsTxDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsRxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsRxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsRxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatserrorsRxDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedTxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedTxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedTxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedTxDeltaAvg"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedRxDelta"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedRxDeltaMin"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedRxDeltaMax"/>
 *             &lt;enumeration value="adaptorVnicStatsdroppedRxDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputRequestsDelta"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputRequestsDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputRequestsDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputRequestsDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputRequestsDelta"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputRequestsDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputRequestsDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputRequestsDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatscontrolRequestsDelta"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatscontrolRequestsDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatscontrolRequestsDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatscontrolRequestsDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputMegabytesDelta"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputMegabytesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputMegabytesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsinputMegabytesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputMegabytesDelta"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputMegabytesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputMegabytesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFC4StatsoutputMegabytesDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatscorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatscorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatscorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatscorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatsuncorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatsuncorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatsuncorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloBaseErrorStatsuncorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropAclDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropAclDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropAclDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropAclDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropOverrunDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropOverrunDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropOverrunDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropOverrunDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropRuntDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropRuntDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropRuntDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatsdropRuntDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatstruncateOverrunDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatstruncateOverrunDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatstruncateOverrunDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuStatstruncateOverrunDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatscorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatscorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatscorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatscorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspopErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspopErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspopErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspopErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspushErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspushErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspushErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatspushErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatsuncorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatsuncorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatsuncorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloMcpuErrorStatsuncorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropOverrunDelta"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropOverrunDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropOverrunDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropOverrunDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropRuntDelta"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropRuntDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropRuntDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthStatsdropRuntDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthStatstruncateOverrunDelta"/>
 *             &lt;enumeration value="adaptorMenloEthStatstruncateOverrunDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthStatstruncateOverrunDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthStatstruncateOverrunDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatscorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatscorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatscorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatscorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsdropAclDelta"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsdropAclDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsdropAclDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsdropAclDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspopErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspopErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspopErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspopErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspushErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspushErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspushErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatspushErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsuncorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsuncorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsuncorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloEthErrorStatsuncorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropAclDelta"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropAclDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropAclDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropAclDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropOverrunDelta"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropOverrunDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropOverrunDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropOverrunDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropRuntDelta"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropRuntDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropRuntDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcStatsdropRuntDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcStatstruncateOverrunDelta"/>
 *             &lt;enumeration value="adaptorMenloFcStatstruncateOverrunDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcStatstruncateOverrunDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcStatstruncateOverrunDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatscorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatscorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatscorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatscorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspopErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspopErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspopErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspopErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspushErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspushErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspushErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatspushErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatsuncorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatsuncorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatsuncorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloFcErrorStatsuncorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN0Delta"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN0DeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN0DeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN0DeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN1Delta"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN1DeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN1DeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQStatsdropOverrunN1DeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN0Delta"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN0DeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN0DeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN0DeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN1Delta"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN1DeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN1DeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQStatstruncateOverrunN1DeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatscorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatscorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatscorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatscorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspopErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspopErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspopErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspopErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspushErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspushErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspushErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatspushErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatsuncorrectableErrorsDelta"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatsuncorrectableErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatsuncorrectableErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloQErrorStatsuncorrectableErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatslearnReqDropDelta"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatslearnReqDropDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatslearnReqDropDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatslearnReqDropDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropCmdDelta"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropCmdDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropCmdDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropCmdDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifCfgInvalidDelta"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifCfgInvalidDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifCfgInvalidDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifCfgInvalidDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifMapNoHitDelta"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifMapNoHitDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifMapNoHitDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropLifMapNoHitDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropSrcBindDelta"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropSrcBindDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropSrcBindDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetEgStatsdropSrcBindDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsfwdLookupNoHitDelta"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsfwdLookupNoHitDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsfwdLookupNoHitDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsfwdLookupNoHitDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcMulticastDelta"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcMulticastDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcMulticastDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcMulticastDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcLifInvalidDelta"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcLifInvalidDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcLifInvalidDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropFcLifInvalidDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropNullPifDelta"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropNullPifDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropNullPifDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloNetInStatsdropNullPifDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPauseCFCDelta"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPauseCFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPauseCFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPauseCFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPausePFCDelta"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPausePFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPausePFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatsrxPausePFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPauseCFCDelta"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPauseCFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPauseCFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPauseCFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPausePFCDelta"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPausePFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPausePFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloHostPortStatstxPausePFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPauseCFCDelta"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPauseCFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPauseCFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPauseCFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPausePFCDelta"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPausePFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPausePFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatsrxPausePFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPauseCFCDelta"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPauseCFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPauseCFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPauseCFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPausePFCDelta"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPausePFCDeltaMin"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPausePFCDeltaMax"/>
 *             &lt;enumeration value="adaptorMenloDcePortStatstxPausePFCDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxBytesDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxBytesDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxBytesDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxBytesDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxPacketsDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxErrorsDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxDroppedDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxDroppedDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxDroppedDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatstxDroppedDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxBytesDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxBytesDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxBytesDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxBytesDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxPacketsDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxErrorsDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxErrorsDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxErrorsDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxErrorsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxDroppedDelta"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxDroppedDeltaMin"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxDroppedDeltaMax"/>
 *             &lt;enumeration value="adaptorEtherIfStatsrxDroppedDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatstxFramesDelta"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatstxFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatstxFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatstxFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsrxFramesDelta"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsrxFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsrxFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsrxFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatserrorFramesDelta"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatserrorFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatserrorFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatserrorFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsdumpedFramesDelta"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsdumpedFramesDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsdumpedFramesDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfFrameStatsdumpedFramesDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslipCountDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslipCountDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslipCountDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslipCountDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsinvalidCRCCountDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsinvalidCRCCountDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsinvalidCRCCountDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsinvalidCRCCountDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsnOSCountDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsnOSCountDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsnOSCountDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsnOSCountDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslinkFailureCountDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslinkFailureCountDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslinkFailureCountDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslinkFailureCountDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSyncCountDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSyncCountDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSyncCountDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSyncCountDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSignalCountDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSignalCountDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSignalCountDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatslossOfSignalCountDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsseqProtocolErrCountDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsseqProtocolErrCountDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsseqProtocolErrCountDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatsseqProtocolErrCountDeltaAvg"/>
 *             &lt;enumeration value="adaptorFcIfEventStatssecondsSinceLastResetDelta"/>
 *             &lt;enumeration value="adaptorFcIfEventStatssecondsSinceLastResetDeltaMin"/>
 *             &lt;enumeration value="adaptorFcIfEventStatssecondsSinceLastResetDeltaMax"/>
 *             &lt;enumeration value="adaptorFcIfEventStatssecondsSinceLastResetDeltaAvg"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet1"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet1Min"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet1Max"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet1Avg"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet2"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet2Min"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet2Max"/>
 *             &lt;enumeration value="swEnvStatsmainBoardOutlet2Avg"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet1"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet1Min"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet1Max"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet1Avg"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet2"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet2Min"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet2Max"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet2Avg"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet3"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet3Min"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet3Max"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet3Avg"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet4"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet4Min"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet4Max"/>
 *             &lt;enumeration value="swEnvStatsfanCtrlrInlet4Avg"/>
 *             &lt;enumeration value="swSystemStatsmemAvailable"/>
 *             &lt;enumeration value="swSystemStatsmemAvailableMin"/>
 *             &lt;enumeration value="swSystemStatsmemAvailableMax"/>
 *             &lt;enumeration value="swSystemStatsmemAvailableAvg"/>
 *             &lt;enumeration value="swSystemStatsmemCached"/>
 *             &lt;enumeration value="swSystemStatsmemCachedMin"/>
 *             &lt;enumeration value="swSystemStatsmemCachedMax"/>
 *             &lt;enumeration value="swSystemStatsmemCachedAvg"/>
 *             &lt;enumeration value="swSystemStatsload"/>
 *             &lt;enumeration value="swSystemStatsloadMin"/>
 *             &lt;enumeration value="swSystemStatsloadMax"/>
 *             &lt;enumeration value="swSystemStatsloadAvg"/>
 *             &lt;enumeration value="etherTxStatstotalBytesDelta"/>
 *             &lt;enumeration value="etherTxStatstotalBytesDeltaMin"/>
 *             &lt;enumeration value="etherTxStatstotalBytesDeltaMax"/>
 *             &lt;enumeration value="etherTxStatstotalBytesDeltaAvg"/>
 *             &lt;enumeration value="etherTxStatstotalPacketsDelta"/>
 *             &lt;enumeration value="etherTxStatstotalPacketsDeltaMin"/>
 *             &lt;enumeration value="etherTxStatstotalPacketsDeltaMax"/>
 *             &lt;enumeration value="etherTxStatstotalPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherTxStatsmulticastPacketsDelta"/>
 *             &lt;enumeration value="etherTxStatsmulticastPacketsDeltaMin"/>
 *             &lt;enumeration value="etherTxStatsmulticastPacketsDeltaMax"/>
 *             &lt;enumeration value="etherTxStatsmulticastPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherTxStatsbroadcastPacketsDelta"/>
 *             &lt;enumeration value="etherTxStatsbroadcastPacketsDeltaMin"/>
 *             &lt;enumeration value="etherTxStatsbroadcastPacketsDeltaMax"/>
 *             &lt;enumeration value="etherTxStatsbroadcastPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherTxStatsjumboPacketsDelta"/>
 *             &lt;enumeration value="etherTxStatsjumboPacketsDeltaMin"/>
 *             &lt;enumeration value="etherTxStatsjumboPacketsDeltaMax"/>
 *             &lt;enumeration value="etherTxStatsjumboPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherRxStatstotalBytesDelta"/>
 *             &lt;enumeration value="etherRxStatstotalBytesDeltaMin"/>
 *             &lt;enumeration value="etherRxStatstotalBytesDeltaMax"/>
 *             &lt;enumeration value="etherRxStatstotalBytesDeltaAvg"/>
 *             &lt;enumeration value="etherRxStatstotalPacketsDelta"/>
 *             &lt;enumeration value="etherRxStatstotalPacketsDeltaMin"/>
 *             &lt;enumeration value="etherRxStatstotalPacketsDeltaMax"/>
 *             &lt;enumeration value="etherRxStatstotalPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherRxStatsunicastPacketsDelta"/>
 *             &lt;enumeration value="etherRxStatsunicastPacketsDeltaMin"/>
 *             &lt;enumeration value="etherRxStatsunicastPacketsDeltaMax"/>
 *             &lt;enumeration value="etherRxStatsunicastPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherRxStatsmulticastPacketsDelta"/>
 *             &lt;enumeration value="etherRxStatsmulticastPacketsDeltaMin"/>
 *             &lt;enumeration value="etherRxStatsmulticastPacketsDeltaMax"/>
 *             &lt;enumeration value="etherRxStatsmulticastPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherRxStatsbroadcastPacketsDelta"/>
 *             &lt;enumeration value="etherRxStatsbroadcastPacketsDeltaMin"/>
 *             &lt;enumeration value="etherRxStatsbroadcastPacketsDeltaMax"/>
 *             &lt;enumeration value="etherRxStatsbroadcastPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherRxStatsjumboPacketsDelta"/>
 *             &lt;enumeration value="etherRxStatsjumboPacketsDeltaMin"/>
 *             &lt;enumeration value="etherRxStatsjumboPacketsDeltaMax"/>
 *             &lt;enumeration value="etherRxStatsjumboPacketsDeltaAvg"/>
 *             &lt;enumeration value="computeMbPowerStatsconsumedPower"/>
 *             &lt;enumeration value="computeMbPowerStatsconsumedPowerMin"/>
 *             &lt;enumeration value="computeMbPowerStatsconsumedPowerMax"/>
 *             &lt;enumeration value="computeMbPowerStatsconsumedPowerAvg"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenIo"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenIoMin"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenIoMax"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenIoAvg"/>
 *             &lt;enumeration value="equipmentChassisStatsinputPower"/>
 *             &lt;enumeration value="equipmentChassisStatsinputPowerMin"/>
 *             &lt;enumeration value="equipmentChassisStatsinputPowerMax"/>
 *             &lt;enumeration value="equipmentChassisStatsinputPowerAvg"/>
 *             &lt;enumeration value="equipmentChassisStatsoutputPower"/>
 *             &lt;enumeration value="equipmentChassisStatsoutputPowerMin"/>
 *             &lt;enumeration value="equipmentChassisStatsoutputPowerMax"/>
 *             &lt;enumeration value="equipmentChassisStatsoutputPowerAvg"/>
 *             &lt;enumeration value="equipmentPsuStatsambientTemp"/>
 *             &lt;enumeration value="equipmentPsuStatsambientTempMin"/>
 *             &lt;enumeration value="equipmentPsuStatsambientTempMax"/>
 *             &lt;enumeration value="equipmentPsuStatsambientTempAvg"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputCurrent"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputCurrentMin"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputCurrentMax"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputCurrentAvg"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputPower"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputPowerMin"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputPowerMax"/>
 *             &lt;enumeration value="equipmentPsuStatsoutputPowerAvg"/>
 *             &lt;enumeration value="equipmentPsuInputStatscurrent"/>
 *             &lt;enumeration value="equipmentPsuInputStatscurrentMin"/>
 *             &lt;enumeration value="equipmentPsuInputStatscurrentMax"/>
 *             &lt;enumeration value="equipmentPsuInputStatscurrentAvg"/>
 *             &lt;enumeration value="equipmentPsuInputStatsvoltage"/>
 *             &lt;enumeration value="equipmentPsuInputStatsvoltageMin"/>
 *             &lt;enumeration value="equipmentPsuInputStatsvoltageMax"/>
 *             &lt;enumeration value="equipmentPsuInputStatsvoltageAvg"/>
 *             &lt;enumeration value="equipmentPsuInputStatspower"/>
 *             &lt;enumeration value="equipmentPsuInputStatspowerMin"/>
 *             &lt;enumeration value="equipmentPsuInputStatspowerMax"/>
 *             &lt;enumeration value="equipmentPsuInputStatspowerAvg"/>
 *             &lt;enumeration value="equipmentFanModuleStatsambientTemp"/>
 *             &lt;enumeration value="equipmentFanModuleStatsambientTempMin"/>
 *             &lt;enumeration value="equipmentFanModuleStatsambientTempMax"/>
 *             &lt;enumeration value="equipmentFanModuleStatsambientTempAvg"/>
 *             &lt;enumeration value="equipmentFanStatsspeed"/>
 *             &lt;enumeration value="equipmentFanStatsspeedMin"/>
 *             &lt;enumeration value="equipmentFanStatsspeedMax"/>
 *             &lt;enumeration value="equipmentFanStatsspeedAvg"/>
 *             &lt;enumeration value="processorRuntimeload"/>
 *             &lt;enumeration value="processorRuntimeloadMin"/>
 *             &lt;enumeration value="processorRuntimeloadMax"/>
 *             &lt;enumeration value="processorRuntimeloadAvg"/>
 *             &lt;enumeration value="fcStatsbytesRxDelta"/>
 *             &lt;enumeration value="fcStatsbytesRxDeltaMin"/>
 *             &lt;enumeration value="fcStatsbytesRxDeltaMax"/>
 *             &lt;enumeration value="fcStatsbytesRxDeltaAvg"/>
 *             &lt;enumeration value="fcStatspacketsRxDelta"/>
 *             &lt;enumeration value="fcStatspacketsRxDeltaMin"/>
 *             &lt;enumeration value="fcStatspacketsRxDeltaMax"/>
 *             &lt;enumeration value="fcStatspacketsRxDeltaAvg"/>
 *             &lt;enumeration value="fcStatsbytesTxDelta"/>
 *             &lt;enumeration value="fcStatsbytesTxDeltaMin"/>
 *             &lt;enumeration value="fcStatsbytesTxDeltaMax"/>
 *             &lt;enumeration value="fcStatsbytesTxDeltaAvg"/>
 *             &lt;enumeration value="fcStatspacketsTxDelta"/>
 *             &lt;enumeration value="fcStatspacketsTxDeltaMin"/>
 *             &lt;enumeration value="fcStatspacketsTxDeltaMax"/>
 *             &lt;enumeration value="fcStatspacketsTxDeltaAvg"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput12v"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput12vMin"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput12vMax"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput12vAvg"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput3v3"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput3v3Min"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput3v3Max"/>
 *             &lt;enumeration value="equipmentPsuStatsoutput3v3Avg"/>
 *             &lt;enumeration value="equipmentPsuStatsinput210v"/>
 *             &lt;enumeration value="equipmentPsuStatsinput210vMin"/>
 *             &lt;enumeration value="equipmentPsuStatsinput210vMax"/>
 *             &lt;enumeration value="equipmentPsuStatsinput210vAvg"/>
 *             &lt;enumeration value="fcErrStatscrcRxDelta"/>
 *             &lt;enumeration value="fcErrStatscrcRxDeltaMin"/>
 *             &lt;enumeration value="fcErrStatscrcRxDeltaMax"/>
 *             &lt;enumeration value="fcErrStatscrcRxDeltaAvg"/>
 *             &lt;enumeration value="equipmentIOCardStatsambientTemp"/>
 *             &lt;enumeration value="equipmentIOCardStatsambientTempMin"/>
 *             &lt;enumeration value="equipmentIOCardStatsambientTempMax"/>
 *             &lt;enumeration value="equipmentIOCardStatsambientTempAvg"/>
 *             &lt;enumeration value="fcErrStatsdiscardRxDelta"/>
 *             &lt;enumeration value="etherErrStatsalignDelta"/>
 *             &lt;enumeration value="etherErrStatsalignDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsalignDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsalignDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatsdiscardRxDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsfcsDelta"/>
 *             &lt;enumeration value="etherErrStatsfcsDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsfcsDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsfcsDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatsdiscardRxDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsxmitDelta"/>
 *             &lt;enumeration value="etherErrStatsxmitDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsxmitDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsxmitDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatsdiscardRxDeltaAvg"/>
 *             &lt;enumeration value="etherErrStatsrcvDelta"/>
 *             &lt;enumeration value="etherErrStatsrcvDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsrcvDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsrcvDeltaAvg"/>
 *             &lt;enumeration value="etherErrStatsunderSizeDelta"/>
 *             &lt;enumeration value="etherErrStatsunderSizeDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsunderSizeDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsunderSizeDeltaAvg"/>
 *             &lt;enumeration value="etherErrStatsoutDiscardDelta"/>
 *             &lt;enumeration value="etherErrStatsoutDiscardDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsoutDiscardDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsoutDiscardDeltaAvg"/>
 *             &lt;enumeration value="etherErrStatsintMacTxDelta"/>
 *             &lt;enumeration value="etherErrStatsintMacTxDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsintMacTxDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsintMacTxDeltaAvg"/>
 *             &lt;enumeration value="etherErrStatsintMacRxDelta"/>
 *             &lt;enumeration value="etherErrStatsintMacRxDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsintMacRxDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsintMacRxDeltaAvg"/>
 *             &lt;enumeration value="etherLossStatssingleCollisionDelta"/>
 *             &lt;enumeration value="etherLossStatssingleCollisionDeltaMin"/>
 *             &lt;enumeration value="etherLossStatssingleCollisionDeltaMax"/>
 *             &lt;enumeration value="etherLossStatssingleCollisionDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatstooLongRxDelta"/>
 *             &lt;enumeration value="etherLossStatsmultiCollisionDelta"/>
 *             &lt;enumeration value="etherLossStatsmultiCollisionDeltaMin"/>
 *             &lt;enumeration value="etherLossStatsmultiCollisionDeltaMax"/>
 *             &lt;enumeration value="etherLossStatsmultiCollisionDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatstooLongRxDeltaMin"/>
 *             &lt;enumeration value="etherLossStatslateCollisionDelta"/>
 *             &lt;enumeration value="etherLossStatslateCollisionDeltaMin"/>
 *             &lt;enumeration value="etherLossStatslateCollisionDeltaMax"/>
 *             &lt;enumeration value="etherLossStatslateCollisionDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatstooLongRxDeltaMax"/>
 *             &lt;enumeration value="fcErrStatstooLongRxDeltaAvg"/>
 *             &lt;enumeration value="etherLossStatscarrierSenseDelta"/>
 *             &lt;enumeration value="etherLossStatscarrierSenseDeltaMin"/>
 *             &lt;enumeration value="etherLossStatscarrierSenseDeltaMax"/>
 *             &lt;enumeration value="etherLossStatscarrierSenseDeltaAvg"/>
 *             &lt;enumeration value="etherLossStatsgiantsDelta"/>
 *             &lt;enumeration value="etherLossStatsgiantsDeltaMin"/>
 *             &lt;enumeration value="etherLossStatsgiantsDeltaMax"/>
 *             &lt;enumeration value="etherLossStatsgiantsDeltaAvg"/>
 *             &lt;enumeration value="etherLossStatssymbolDelta"/>
 *             &lt;enumeration value="etherLossStatssymbolDeltaMin"/>
 *             &lt;enumeration value="etherLossStatssymbolDeltaMax"/>
 *             &lt;enumeration value="etherLossStatssymbolDeltaAvg"/>
 *             &lt;enumeration value="etherLossStatsSQETestDelta"/>
 *             &lt;enumeration value="etherLossStatsSQETestDeltaMin"/>
 *             &lt;enumeration value="etherLossStatsSQETestDeltaMax"/>
 *             &lt;enumeration value="etherLossStatsSQETestDeltaAvg"/>
 *             &lt;enumeration value="etherPauseStatsrecvPauseDelta"/>
 *             &lt;enumeration value="etherPauseStatsrecvPauseDeltaMin"/>
 *             &lt;enumeration value="etherPauseStatsrecvPauseDeltaMax"/>
 *             &lt;enumeration value="etherPauseStatsrecvPauseDeltaAvg"/>
 *             &lt;enumeration value="etherPauseStatsxmitPauseDelta"/>
 *             &lt;enumeration value="etherPauseStatsxmitPauseDeltaMin"/>
 *             &lt;enumeration value="etherPauseStatsxmitPauseDeltaMax"/>
 *             &lt;enumeration value="etherPauseStatsxmitPauseDeltaAvg"/>
 *             &lt;enumeration value="etherPauseStatsresetsDelta"/>
 *             &lt;enumeration value="etherPauseStatsresetsDeltaMin"/>
 *             &lt;enumeration value="etherPauseStatsresetsDeltaMax"/>
 *             &lt;enumeration value="fcErrStatstooShortRxDelta"/>
 *             &lt;enumeration value="etherPauseStatsresetsDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatstooShortRxDeltaMin"/>
 *             &lt;enumeration value="fcErrStatstooShortRxDeltaMax"/>
 *             &lt;enumeration value="etherLossStatsexcessCollisionDelta"/>
 *             &lt;enumeration value="etherLossStatsexcessCollisionDeltaMin"/>
 *             &lt;enumeration value="etherLossStatsexcessCollisionDeltaMax"/>
 *             &lt;enumeration value="etherLossStatsexcessCollisionDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatstooShortRxDeltaAvg"/>
 *             &lt;enumeration value="etherTxStatsunicastPacketsDelta"/>
 *             &lt;enumeration value="etherTxStatsunicastPacketsDeltaMin"/>
 *             &lt;enumeration value="etherTxStatsunicastPacketsDeltaMax"/>
 *             &lt;enumeration value="etherTxStatsunicastPacketsDeltaAvg"/>
 *             &lt;enumeration value="etherErrStatsdeferredTxDelta"/>
 *             &lt;enumeration value="etherErrStatsdeferredTxDeltaMin"/>
 *             &lt;enumeration value="etherErrStatsdeferredTxDeltaMax"/>
 *             &lt;enumeration value="etherErrStatsdeferredTxDeltaAvg"/>
 *             &lt;enumeration value="computeMbPowerStatsinputVoltage"/>
 *             &lt;enumeration value="computeMbPowerStatsinputVoltageMin"/>
 *             &lt;enumeration value="computeMbPowerStatsinputVoltageMax"/>
 *             &lt;enumeration value="computeMbPowerStatsinputVoltageAvg"/>
 *             &lt;enumeration value="computeMbPowerStatsinputCurrent"/>
 *             &lt;enumeration value="computeMbPowerStatsinputCurrentMin"/>
 *             &lt;enumeration value="computeMbPowerStatsinputCurrentMax"/>
 *             &lt;enumeration value="computeMbPowerStatsinputCurrentAvg"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRear"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearMin"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearMax"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearAvg"/>
 *             &lt;enumeration value="memoryUnitEnvStatstemperature"/>
 *             &lt;enumeration value="memoryUnitEnvStatstemperatureMin"/>
 *             &lt;enumeration value="memoryUnitEnvStatstemperatureMax"/>
 *             &lt;enumeration value="memoryUnitEnvStatstemperatureAvg"/>
 *             &lt;enumeration value="fcErrStatsrxDelta"/>
 *             &lt;enumeration value="processorEnvStatstemperature"/>
 *             &lt;enumeration value="processorEnvStatstemperatureMin"/>
 *             &lt;enumeration value="processorEnvStatstemperatureMax"/>
 *             &lt;enumeration value="processorEnvStatstemperatureAvg"/>
 *             &lt;enumeration value="fcErrStatsrxDeltaMin"/>
 *             &lt;enumeration value="fcErrStatsrxDeltaMax"/>
 *             &lt;enumeration value="fcErrStatsrxDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatsdiscardTxDelta"/>
 *             &lt;enumeration value="fcErrStatsdiscardTxDeltaMin"/>
 *             &lt;enumeration value="fcErrStatsdiscardTxDeltaMax"/>
 *             &lt;enumeration value="fcErrStatsdiscardTxDeltaAvg"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet1"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet1Min"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet1Max"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet1Avg"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet2"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet2Min"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet2Max"/>
 *             &lt;enumeration value="swEnvStatspsuCtrlrInlet2Avg"/>
 *             &lt;enumeration value="fcErrStatstxDelta"/>
 *             &lt;enumeration value="fcErrStatstxDeltaMin"/>
 *             &lt;enumeration value="fcErrStatstxDeltaMax"/>
 *             &lt;enumeration value="fcErrStatstxDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatslinkFailuresDelta"/>
 *             &lt;enumeration value="fcErrStatslinkFailuresDeltaMin"/>
 *             &lt;enumeration value="fcErrStatslinkFailuresDeltaMax"/>
 *             &lt;enumeration value="fcErrStatslinkFailuresDeltaAvg"/>
 *             &lt;enumeration value="fcErrStatssyncLossesDelta"/>
 *             &lt;enumeration value="fcErrStatssyncLossesDeltaMin"/>
 *             &lt;enumeration value="computePCIeFatalProtocolStatsdllpErrors"/>
 *             &lt;enumeration value="fcErrStatssyncLossesDeltaMax"/>
 *             &lt;enumeration value="computePCIeFatalProtocolStatsflowControlErrors"/>
 *             &lt;enumeration value="fcErrStatssyncLossesDeltaAvg"/>
 *             &lt;enumeration value="computePCIeFatalReceiveStatsunsupportedRequestErrors"/>
 *             &lt;enumeration value="computePCIeFatalReceiveStatserrFatalErrors"/>
 *             &lt;enumeration value="computePCIeFatalReceiveStatserrNonFatalErrors"/>
 *             &lt;enumeration value="computePCIeFatalCompletionStatsunexpectedErrors"/>
 *             &lt;enumeration value="computePCIeFatalCompletionStatsTimeoutErrors"/>
 *             &lt;enumeration value="computePCIeFatalCompletionStatsAbortErrors"/>
 *             &lt;enumeration value="fcErrStatssignalLossesDelta"/>
 *             &lt;enumeration value="fcErrStatssignalLossesDeltaMin"/>
 *             &lt;enumeration value="fcErrStatssignalLossesDeltaMax"/>
 *             &lt;enumeration value="computePCIeFatalStatssurpriseLinkDownErrors"/>
 *             &lt;enumeration value="fcErrStatssignalLossesDeltaAvg"/>
 *             &lt;enumeration value="computePCIeFatalStatspoisonedTLPErrors"/>
 *             &lt;enumeration value="computePCIeFatalStatsacsViolationErrors"/>
 *             &lt;enumeration value="computePCIeFatalStatsmalformedTLPErrors"/>
 *             &lt;enumeration value="equipmentIOCardStatstemp"/>
 *             &lt;enumeration value="equipmentIOCardStatstempMin"/>
 *             &lt;enumeration value="equipmentIOCardStatstempMax"/>
 *             &lt;enumeration value="equipmentIOCardStatstempAvg"/>
 *             &lt;enumeration value="processorEnvStatsinputCurrent"/>
 *             &lt;enumeration value="processorEnvStatsinputCurrentMin"/>
 *             &lt;enumeration value="processorEnvStatsinputCurrentMax"/>
 *             &lt;enumeration value="processorEnvStatsinputCurrentAvg"/>
 *             &lt;enumeration value="memoryArrayEnvStatsinputCurrent"/>
 *             &lt;enumeration value="memoryArrayEnvStatsinputCurrentMin"/>
 *             &lt;enumeration value="memoryArrayEnvStatsinputCurrentMax"/>
 *             &lt;enumeration value="memoryArrayEnvStatsinputCurrentAvg"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsnoBreakdownGreaterThan1518Delta"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsnoBreakdownGreaterThan1518DeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsnoBreakdownGreaterThan1518DeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortBySizeLargeStatsnoBreakdownGreaterThan1518DeltaAvg"/>
 *             &lt;enumeration value="memoryBufferUnitEnvStatstemperature"/>
 *             &lt;enumeration value="memoryBufferUnitEnvStatstemperatureMin"/>
 *             &lt;enumeration value="memoryBufferUnitEnvStatstemperatureMax"/>
 *             &lt;enumeration value="memoryBufferUnitEnvStatstemperatureAvg"/>
 *             &lt;enumeration value="computeIOHubEnvStatstemperature"/>
 *             &lt;enumeration value="computeIOHubEnvStatstemperatureMin"/>
 *             &lt;enumeration value="computeIOHubEnvStatstemperatureMax"/>
 *             &lt;enumeration value="computeIOHubEnvStatstemperatureAvg"/>
 *             &lt;enumeration value="processorErrorStatsmirroringIntraSockErrors"/>
 *             &lt;enumeration value="processorErrorStatsmirroringInterSockErrors"/>
 *             &lt;enumeration value="processorErrorStatssparingErrors"/>
 *             &lt;enumeration value="processorErrorStatssmiLinkCorrErrors"/>
 *             &lt;enumeration value="processorErrorStatssmiLinkUncorrErrors"/>
 *             &lt;enumeration value="memoryErrorStatseccMultibitErrors"/>
 *             &lt;enumeration value="memoryErrorStatseccSinglebitErrors"/>
 *             &lt;enumeration value="memoryErrorStatsaddressParityErrors"/>
 *             &lt;enumeration value="memoryErrorStatsmismatchErrors"/>
 *             &lt;enumeration value="computePCIeFatalReceiveStatsbufferOverflowErrors"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearL"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearLMin"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearLMax"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearLAvg"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearR"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearRMin"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearRMax"/>
 *             &lt;enumeration value="computeMbTempStatsfmTempSenRearRAvg"/>
 *             &lt;enumeration value="powerGroupStatspower"/>
 *             &lt;enumeration value="powerGroupStatspowerMin"/>
 *             &lt;enumeration value="powerGroupStatspowerMax"/>
 *             &lt;enumeration value="powerGroupStatspowerAvg"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet1"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet1Min"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet1Max"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet1Avg"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet2"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet2Min"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet2Max"/>
 *             &lt;enumeration value="equipmentFexEnvStatsoutlet2Avg"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinlet"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinletMin"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinletMax"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinletAvg"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinlet1"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinlet1Min"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinlet1Max"/>
 *             &lt;enumeration value="equipmentFexEnvStatsinlet1Avg"/>
 *             &lt;enumeration value="equipmentFexEnvStatsdie1"/>
 *             &lt;enumeration value="equipmentFexEnvStatsdie1Min"/>
 *             &lt;enumeration value="equipmentFexEnvStatsdie1Max"/>
 *             &lt;enumeration value="equipmentFexEnvStatsdie1Avg"/>
 *             &lt;enumeration value="equipmentFexPowerSummarytotalPower"/>
 *             &lt;enumeration value="equipmentFexPowerSummarytotalPowerMin"/>
 *             &lt;enumeration value="equipmentFexPowerSummarytotalPowerMax"/>
 *             &lt;enumeration value="equipmentFexPowerSummarytotalPowerAvg"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryreservedPower"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryreservedPowerMin"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryreservedPowerMax"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryreservedPowerAvg"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryModulePower"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryModulePowerMin"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryModulePowerMax"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryModulePowerAvg"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryavailablePower"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryavailablePowerMin"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryavailablePowerMax"/>
 *             &lt;enumeration value="equipmentFexPowerSummaryavailablePowerAvg"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatscurrent"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatscurrentMin"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatscurrentMax"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatscurrentAvg"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatsvoltage"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatsvoltageMin"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatsvoltageMax"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatsvoltageAvg"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatspower"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatspowerMin"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatspowerMax"/>
 *             &lt;enumeration value="equipmentFexPsuInputStatspowerAvg"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsambientTemp"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsambientTempMin"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsambientTempMax"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsambientTempAvg"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputCurrent"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputCurrentMin"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputCurrentMax"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputCurrentAvg"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputPower"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputPowerMin"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputPowerMax"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputPowerAvg"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputPower"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputPowerMin"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputPowerMax"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputPowerAvg"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputVoltage"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputVoltageMin"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputVoltageMax"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsoutputVoltageAvg"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputVoltage"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputVoltageMin"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputVoltageMax"/>
 *             &lt;enumeration value="equipmentRackUnitPsuStatsinputVoltageAvg"/>
 *             &lt;enumeration value="equipmentRackUnitFanStatsspeed"/>
 *             &lt;enumeration value="equipmentRackUnitFanStatsspeedMin"/>
 *             &lt;enumeration value="equipmentRackUnitFanStatsspeedMax"/>
 *             &lt;enumeration value="equipmentRackUnitFanStatsspeedAvg"/>
 *             &lt;enumeration value="memoryRuntimetotal"/>
 *             &lt;enumeration value="memoryRuntimetotalMin"/>
 *             &lt;enumeration value="memoryRuntimetotalMax"/>
 *             &lt;enumeration value="memoryRuntimetotalAvg"/>
 *             &lt;enumeration value="memoryRuntimeavailable"/>
 *             &lt;enumeration value="memoryRuntimeavailableMin"/>
 *             &lt;enumeration value="memoryRuntimeavailableMax"/>
 *             &lt;enumeration value="memoryRuntimeavailableAvg"/>
 *             &lt;enumeration value="memoryRuntimecached"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsfrontTemp"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsfrontTempMin"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsfrontTempMax"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsfrontTempAvg"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsrearTemp"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsrearTempMin"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsrearTempMax"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsrearTempAvg"/>
 *             &lt;enumeration value="memoryRuntimecachedMin"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsambientTemp"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsambientTempMin"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsambientTempMax"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsambientTempAvg"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh1Temp"/>
 *             &lt;enumeration value="memoryRuntimecachedMax"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh1TempMin"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh1TempMax"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh1TempAvg"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh2Temp"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh2TempMin"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh2TempMax"/>
 *             &lt;enumeration value="memoryRuntimecachedAvg"/>
 *             &lt;enumeration value="computeRackUnitMbTempStatsioh2TempAvg"/>
 *             &lt;enumeration value="adaptorEthPortStatstotalPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortStatstotalPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortStatstotalPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortStatstotalPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortStatsgoodPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortStatsgoodPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortStatsgoodPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortStatsgoodPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortStatsvlanPacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortStatsvlanPacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortStatsvlanPacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortStatsvlanPacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortStatspausePacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortStatspausePacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortStatspausePacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortStatspausePacketsDeltaAvg"/>
 *             &lt;enumeration value="adaptorEthPortStatsperPriorityPausePacketsDelta"/>
 *             &lt;enumeration value="adaptorEthPortStatsperPriorityPausePacketsDeltaMin"/>
 *             &lt;enumeration value="adaptorEthPortStatsperPriorityPausePacketsDeltaMax"/>
 *             &lt;enumeration value="adaptorEthPortStatsperPriorityPausePacketsDeltaAvg"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="descr">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[ !#$%&amp;\(\)\*\+,\-\./:;\?@\[\]_\{\|\}~a-zA-Z0-9]{0,256}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[\-\.:_a-zA-Z0-9]{0,16}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dn" type="{}referenceObject" />
 *       &lt;attribute name="rn" type="{}referenceRn" />
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="((removed|created|modified|deleted),){0,3}(removed|created|modified|deleted){0,1}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statsThr64Definition", propOrder = {
    "content"
})
public class StatsThr64Definition {

    @XmlElementRefs({
        @XmlElementRef(name = "statsThrFloatValue", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "statsThr32Value", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "statsThr64Value", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "normalValue")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger normalValue;
    @XmlAttribute(name = "propId")
    protected String propId;
    @XmlAttribute(name = "descr")
    protected String descr;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "dn")
    protected String dn;
    @XmlAttribute(name = "rn")
    protected String rn;
    @XmlAttribute(name = "status")
    protected String status;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link StatsThrFloatValue }{@code >}
     * {@link JAXBElement }{@code <}{@link StatsThr32Value }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link StatsThr64Value }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the normalValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNormalValue() {
        return normalValue;
    }

    /**
     * Sets the value of the normalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNormalValue(BigInteger value) {
        this.normalValue = value;
    }

    /**
     * Gets the value of the propId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropId() {
        return propId;
    }

    /**
     * Sets the value of the propId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropId(String value) {
        this.propId = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescr() {
        return descr;
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescr(String value) {
        this.descr = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDn() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDn(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the rn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRn() {
        return rn;
    }

    /**
     * Sets the value of the rn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRn(String value) {
        this.rn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
