//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.27 at 10:49:34 AM PDT 
//


package com.appdynamics.demo.metricservice.integration.ucs.in;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for syntheticFile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="syntheticFile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="atime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="blksize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="blocks" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="ctime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="dev" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="gid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="ino" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="mtime" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="0"/>
 *             &lt;maxLength value="510"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nlink" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="path">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="0"/>
 *             &lt;maxLength value="510"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rdev" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="uid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="dn" type="{}referenceObject" />
 *       &lt;attribute name="rn" type="{}referenceRn" />
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="((removed|created|modified|deleted),){0,3}(removed|created|modified|deleted){0,1}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "syntheticFile", propOrder = {
    "content"
})
public class SyntheticFile {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "atime")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger atime;
    @XmlAttribute(name = "blksize")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger blksize;
    @XmlAttribute(name = "blocks")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger blocks;
    @XmlAttribute(name = "ctime")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger ctime;
    @XmlAttribute(name = "dev")
    @XmlSchemaType(name = "unsignedInt")
    protected Long dev;
    @XmlAttribute(name = "gid")
    @XmlSchemaType(name = "unsignedInt")
    protected Long gid;
    @XmlAttribute(name = "ino")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger ino;
    @XmlAttribute(name = "mode")
    @XmlSchemaType(name = "unsignedInt")
    protected Long mode;
    @XmlAttribute(name = "mtime")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger mtime;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "nlink")
    @XmlSchemaType(name = "unsignedInt")
    protected Long nlink;
    @XmlAttribute(name = "path")
    protected String path;
    @XmlAttribute(name = "rdev")
    @XmlSchemaType(name = "unsignedInt")
    protected Long rdev;
    @XmlAttribute(name = "size")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger size;
    @XmlAttribute(name = "uid")
    @XmlSchemaType(name = "unsignedInt")
    protected Long uid;
    @XmlAttribute(name = "dn")
    protected String dn;
    @XmlAttribute(name = "rn")
    protected String rn;
    @XmlAttribute(name = "status")
    protected String status;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the atime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAtime() {
        return atime;
    }

    /**
     * Sets the value of the atime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAtime(BigInteger value) {
        this.atime = value;
    }

    /**
     * Gets the value of the blksize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBlksize() {
        return blksize;
    }

    /**
     * Sets the value of the blksize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBlksize(BigInteger value) {
        this.blksize = value;
    }

    /**
     * Gets the value of the blocks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBlocks() {
        return blocks;
    }

    /**
     * Sets the value of the blocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBlocks(BigInteger value) {
        this.blocks = value;
    }

    /**
     * Gets the value of the ctime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCtime() {
        return ctime;
    }

    /**
     * Sets the value of the ctime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCtime(BigInteger value) {
        this.ctime = value;
    }

    /**
     * Gets the value of the dev property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDev() {
        return dev;
    }

    /**
     * Sets the value of the dev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDev(Long value) {
        this.dev = value;
    }

    /**
     * Gets the value of the gid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getGid() {
        return gid;
    }

    /**
     * Sets the value of the gid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setGid(Long value) {
        this.gid = value;
    }

    /**
     * Gets the value of the ino property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIno() {
        return ino;
    }

    /**
     * Sets the value of the ino property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIno(BigInteger value) {
        this.ino = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMode(Long value) {
        this.mode = value;
    }

    /**
     * Gets the value of the mtime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMtime() {
        return mtime;
    }

    /**
     * Sets the value of the mtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMtime(BigInteger value) {
        this.mtime = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nlink property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNlink() {
        return nlink;
    }

    /**
     * Sets the value of the nlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNlink(Long value) {
        this.nlink = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the rdev property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRdev() {
        return rdev;
    }

    /**
     * Sets the value of the rdev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRdev(Long value) {
        this.rdev = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUid(Long value) {
        this.uid = value;
    }

    /**
     * Gets the value of the dn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDn() {
        return dn;
    }

    /**
     * Sets the value of the dn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDn(String value) {
        this.dn = value;
    }

    /**
     * Gets the value of the rn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRn() {
        return rn;
    }

    /**
     * Sets the value of the rn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRn(String value) {
        this.rn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
